Repository ember-learn/guidemaker-ember-template, pull requests merged in 2024-07, with the labels that each got.

#194 fix: add styling for video element
  guidemaker-ember-template/src/styles/addon.css
  test-app/guides/release/examples/video.md
  test-app/guides/release/pages.yml
  test-app/tests/acceptance/chapter-links-test.js
Labels: bug

#200 fix: align anchors icons and adjust size
  guidemaker-ember-template/src/styles/addon.css
Labels: enhancement

#201 Update README.md
  README.md
Labels: documentation

#203 Transform chapter-links to glimmer component
  guidemaker-ember-template/src/components/chapter-links.hbs
  guidemaker-ember-template/src/components/chapter-links.js
  guidemaker-ember-template/src/components/guides-article.hbs
  test-app/tests/acceptance/chapter-links-test.js
  test-app/tests/integration/components/chapter-links-test.js
Labels: enhancement

#204 refactor: transoform search-result to glimmer component
  guidemaker-ember-template/src/components/search-result.hbs
  guidemaker-ember-template/src/components/search-result.js
  test-app/tests/integration/components/search-result-test.js
Labels: enhancement
